testthat::test_that("Correct function output", {
  testthat::expect_s3_class(pr_get_NRSChemistry(), "data.frame")
  testthat::expect_s3_class(pr_get_NRSPigments(), "data.frame")
  testthat::expect_s3_class(pr_get_NRSPigments(Format = "binned"), "data.frame")
  testthat::expect_s3_class(pr_get_NRSPico(), "data.frame")
  testthat::expect_s3_class(pr_get_NRSMicro(Survey = "NRS"), "data.frame")
  testthat::expect_s3_class(pr_get_NRSMicro(Survey = "Coastal"), "data.frame")
  testthat::expect_s3_class(pr_get_NRSMicro(Survey = "GO-SHIP"), "data.frame")
  testthat::expect_s3_class(pr_get_CSChem(), "data.frame")
  testthat::expect_s3_class(pr_get_NRSTSS(), "data.frame")
  testthat::expect_s3_class(pr_get_NRSCTD(), "data.frame")
  testthat::expect_s3_class(pr_get_LTnuts(), "data.frame")
  testthat::expect_s3_class (pr_get_NRSEnvContour(Data = "Pico"), "data.frame")
})
