
#' Rename variables within dataframe
#'
#' @param df Dataframe with column names to renamed
#'
#' @return Dataframe with new column names
#'
pr_rename <- function(df){

  rename_df <- tibble::as_tibble(matrix(c(
    "Ammonium_umolL", "AMMONIUM_UMOLL",
    "BioVolume_um3m3", "BIOVOL_UM3M3",
    "Biomass_mgm3", "BIOMASS_MGM3",
    "Biovolume_um3L", "BIOVOLUME_UM3L",
    "CTDChlF_mgm", "Chla_mgm",
    "CTDSalinity", "Salinity_psu",
    "CTDTemperature", "Temperature_degC",
    # "CTDChlF_mgm3"
    "Cells_L", "CELL_L",
    "Chla_flag", "CPHL_quality_control",
    "Chla_mgm3", "CPHL",
    # "ChlorophyllSatellite_mgm", "CHLA",
    "Comments", "COMMENTS",
    "Conductivity_Sm", "CNDC",
    "Conductivity_flag", "CNDC_quality_control",
    "Copepod", "COPEPOD",
    "Date", "SampleDateLocal",
    "DIC_umolkg", "DIC_UMOLKG",
    "DissolvedOxygen_flag", "DOX2_quality_control",
    "DissolvedOxygen_umolkg", "DOX2",
    "EndLatitude", "ENDLATITUDE",
    "EndLongitude", "ENDLONGITUDE",
    "EndSampleDateUTC", "ENDSAMPLEDATEUTC",
    "FlagComments", "FLAG_COMMENT",
    "FovCount", "FOV_COUNT",
    "GearDepth_m", "GEARDEPTH_M",
    "GearMesh_um", "GEARMESH_UM",
    "Genus", "GENUS",
    "InorganicFraction_mgL", "INORGANIC_FRACTION_MG_PER_L", ##***
    # "InorganicFraction_mgL", "INORGANICFRACTION_MGL",
    "Latitude", "LATITUDE",
    "Longitude", "LONGITUDE",
    "Nitrate_umolL", "NITRATE_UMOLL",
    "Nitrite_umolL", "NITRITE_UMOLL",
    "OrganicFraction_mgL", "ORGANIC_FRACTION_MG_PER_L",
    # "OrganicFraction_mgL", "ORGANICFRACTION_MGL",
    "Oxygen_umolL", "OXYGEN_UMOLL",
    "ParentName", "PARENT_NAME",
    "Phosphate_umolL", "PHOSPHATE_UMOLL",
    "PhytoAbund_m3", "PHYTO_ABUNDANCE_M3",
    "PhytoSampleDepth_m", "PHYTOSAMPLEDEPTH_M",
    "Picoeukaryotes_Cellsml", "PICOEUKARYOTES_CELLSML",
    "Picoeukaryotes_Flag", "PICOEUKARYOTES_FLAG",
    "PigmentsComments", "PIGMENTS_COMMENTS",
    "PigmentsFlag", "PIGMENTS_FLAG",
    "Pressure_dbar", "PRES_REL",
    "Prochlorococcus_Cellsml", "PROCHLOROCOCCUS_CELLSML",
    "Prochlorococcus_Flag", "PROCHLOROCOCCUS_FLAG",
    "ProjectName", "PROJECTNAME",
    "Replicate", "REPLICATE",
    "SPCode", "SPCODE",
    # "Salinity_flag", "PSAL_quality_control",
    "Salinity_psu", "SALINITY_PSU", ## ****
    "SampVol_L", "SAMPVOL_L",
    "SampVol_m3", "SAMPVOL_M3", ###******
    "Sample", "SAMPLE",
    "SampleDateUTC", "SAMPLEDATEUTC",
    "SampleDateLocal", "SAMPLEDATELOCAL",
    "SampleDepth_m", "SAMPLEDEPTH_M",
    # "SampleDepth_m", "DEPTH",
    "SampleType", "SAMPLETYPE",
    "ScientificName", "SCIENTIFICNAME",
    # "Secchi_m", "SECCHIDEPTH_M",
    "Secchi_m", "SECCHI_M",
    "Silicate_umolL", "SILICATE_UMOLL",
    "Species", "SPECIES",
    "StartDate", "STARTDATE",
    # "StartDate", "START_DATE",
    "StartLatitude", "STARTLATITUDE",
    "StartLongitude", "STARTLONGITUDE",
    "StartSampleDateUTC", "STARTSAMPLEDATEUTC",
    "StationName", "STATIONNAME",
    "StationCode", "STATIONCODE",
    "StationDepth_m", "STATIONDEPTH_M",
    "Synecochoccus_Cellsml", "SYNECOCHOCCUS_CELLSML",
    "Synecochoccus_Flag", "SYNECOCHOCCUS_FLAG",
    "TAlkalinity_umolkg", "TALKALINITY_UMOLKG",
    "TSS_Comments", "TSS_COMMENTS",
    "TSS_Flag", "TSS_FLAG",
    # "TSS_mgL", "TSS_MGL",
    "TSS_mgL", "TSS_MG_PER_L",
    "TaxonCount", "TAXON_COUNT",
    "TaxonGroup", "TAXON_GROUP",
    "TaxonName", "TAXON_NAME",
    "Temperature_degC", "TEMPERATURE_C",
    "Temperature_flag", "TEMP_quality_control",
    "TowType", "TOWTYPE",
    "TripCode", "TRIP_CODE",
    "Turbidity_NTU", "TURB",
    "Turbidity_flag", "TURB_quality_control",
    "Vessel", "VESSEL",
    "Volume_m3", "VOLUME_M3",
    "WaterDensity_flag", "DENS_quality_control",
    "WaterDensity_kgm3", "DENS",
    "WaterDepth_m", "DEPTH_M",
    "ZooPhytoAbund_m3", "ZOOP_ABUNDANCE_M3",
    "ZoopSampleDepth_m", "ZOOPSAMPLEDEPTH_M",
    "i_Sample", "I_SAMPLE_ID"),
    ncol = 2, byrow = TRUE, dimnames = list(NULL, c("New","Old"))))

  df <- data.table::setnames(df, old = rename_df$Old, new = rename_df$New, skip_absent = TRUE)

  return(df)
}
