
#' Rename variables within dataframe
#'
#' @param df Dataframe with column names to renamed
#' @export
#'
#' @return Dataframe with new column names
#' @examples
#' df <- data.frame(LATITUDE = -32, LONGITUDE = 160) %>%
#'             pr_rename()
pr_rename <- function(df){

  ##TODO - Check and remvoe any uneeded renames - note the capitals are needed for files grabbed from S3
  rename_df <- tibble::as_tibble(matrix(c(
    "Sample", "SAMPLE",
    "Region", "REGION",
    "AshFreeBiomass_mgm3", "ASHFREEBIOMASS_MGM3",
    "Biomass_mgm3", "BIOMASS_MGM3",
    "Cell BioVolume (um3)", "BV_CELL",
    "Cell Carbon (pgN cell-1)", "PGC_CELL",
    "Cell Nitrogen (pgN cell-1)", "MONT2001PGN_CELL",
    "Diet", "DIET",
    "Feeding", "TROPHY",
    "Functional Group", "FUNCTIONALGROUP",
    "Genus", "GENUS",
    "Latitude", "LATITUDE",
    "Longitude", "LONGITUDE",
    "Length (mm)", "LENGTH_MM",
    "Methods", "METHODS",
    "Nitrate_umolL", "NITRATE_VALUE",
    "Nitrate_Flag", "NITRATE_QC_FLAG",
    "Nitrite_umolL", "NITRITE_VALUE",
    "Nitrite_Flag", "NITRITE_QC_FLAG",
    "Oxygen_umolL", "OXYGEN_VALUE",
    "Oxygen_Flag", "OXYGEN_QC_FLAG",
    "Phosphate_umolL", "PHOSPHATE_VALUE",
    "Phosphate_Flag", "PHOSPHATE_QC_FLAG",
    "Reference (Size)", "SIZEREFERENCE",
    "SampleTime_UTC", "SAMPLEDATEUTC",  # put these back as they come from S3 pr_get_CPRtrips()
    "SampleTime_Local", "SAMPLEDATELOCAL",
    "Salinity", "SALINITY_VALUE",
    "Salinity_Flag", "SALINITY_QC_FLAG",
    "Silicate_umolL", "SILICATE_VALUE",
    "Silicate_Flag", "SILICATE_QC_FLAG",
    "Species", "SPECIES",
    "Temperature_degC", "TEMPERATURE_VALUE",
    "Temperature_Flag", "TEMPERATURE_QC_FLAG",
    "Ammonium_umolL", "AMMONIA_VALUE",
    "Ammonium_Flag", "AMMONIA_QC_FLAG",
    "ProjectName", "PROJECTNAME",
    "PSampleDepth_m", "PHYTOSAMPLEDEPTH_M",
    "SampleType", "SAMPLETYPE",
    "Secchi_m", "SECCHI_M",
    "StationName", "STATIONNAME",
    "StationCode", "STATIONCODE",
    "Sub Genera", "SUBGENERA",
    "Taxon Name", "TAXON_NAME",
    "TripCode", "TRIP_CODE",
    "WoRMS Sp. Code", "SPCODE",
    "ZSampleDepth_m", "ZOOPSAMPLEDEPTH_M"),
    ncol = 2, byrow = TRUE, dimnames = list(NULL, c("New","Old"))))

  df <- data.table::setnames(df, old = rename_df$Old, new = rename_df$New, skip_absent = TRUE)

  return(df)
}

# "Year", "Year_local",
# "Month", "Month_local",
# "Day", "Day_local",
# "Time", "Time_local24hr",
# "Ammonium_flag", "AMMONIUM_FLAG",
# "Ammonium_umolL", "AMMONIUM_UMOLL",
# "BioVolume_um3m3", "BIOVOL_UM3M3",
# "Biovolume_um3L", "BIOVOLUME_UM3L",
# "BottomDepth_m","BOT_DEPTH",
# "BottomDepth_flag", "BOT_DEPTH_quality_control",
# "CAABCode","CAAB_CODE",
# "Cells_L", "CELL_L",
# "ChlF_mgm3", "CHLF",
# "ChlF_flag", "CHLF_quality_control",
# "ChlU","CHLU",
# "ChlU_flag", "CHLU_quality_control",
# "Chla_flag", "CPHL_quality_control",
# "Chla_mgm3", "CPHL",
# "Comments", "COMMENTS",
# "Conductivity_Sm", "CNDC",
# "Conductivity_flag", "CNDC_quality_control",
# "Copepod", "COPEPOD", # "Density_kgm3", "WaterDensity_kgm3",
# "Depth_m", "DEPTH",
# "Depth_flag", "DEPTH_quality_control",
# "DIC_Comments", "CARBON_COMMENTS",
# "DIC_flag", "CARBON_FLAG",
# "DIC_umolkg", "DIC_UMOLKG",
# "Diet", "DIET",
# "DissolvedOxygen_flag", "DOX2_quality_control",
# "DissolvedOxygen_umolkg", "DOX2",
# "Family", "FAMILY",
# "FlagComments", "FLAG_COMMENT",
# "FlagQC", "QC_FLAG",
# "FovCount", "FOV_COUNT",
# "GearDepth_m", "GEARDEPTH_M",
# "GearMesh_um", "GEARMESH_UM",
# "Genus", "GENUS",
# "InorganicFraction_mgL", "INORGANICFRACTION_MGL",
# "Latitude_flag", "LATITUDE_quality_control",
# "Length_mm", "LENGTH_MM",
# "Longitude_flag", "LONGITUDE_quality_control",
# "TaxonGroup","TAXON_ECO_GROUP",
# "Temperature_degC","TEMP",
# "TripCode", "NRS_TRIP_CODE",
# "StationCode", "STATIONCODE",
# "SampleCode", "NRS_SAMPLE_CODE",
# "SiteCode", "IMOS_SITE_CODE",
# "SampleTime_UTC", "time_coverage_start",
# "TaxonTraining", "TAXON_TRAINING",
# "TaxonComments", "TAXON_COMMENTS",
# "Salinity_psu", "PSAL",
# "Salinity_flag", "PSAL_quality_control"
# "Nitrate_flag", "NITRATE_FLAG",
# "Nitrate_umolL", "NITRATE_UMOLL",
# "Nitrite_flag", "NITRITE_FLAG",
# "Nitrite_umolL", "NITRITE_UMOLL",
# "Nutrient_Comments", "NUTRIENT_COMMENTS",
# "OrganicFraction_mgL", "ORGANICFRACTION_MGL",
# "Oxygen_flag", "OXYGEN_FLAG",
# "Oxygen_umolL", "OXYGEN_UMOLL",
# "Oxygen_Comments", "OXYGEN_COMMENTS",
# "ParentName", "PARENT_NAME",
# "Phosphate_umolL", "PHOSPHATE_UMOLL",
# "Phosphate_flag", "PHOSPHATE_FLAG",
# "PhytoAbund_m3", "PHYTO_ABUNDANCE_M3",
# # "Picoeukaryotes_CellsmL", "Picoeukar_cellsmL",
# # "Picoeukaryotes_flag", "Picoeukar_flag",
# "PigmentsComments", "PIGMENTS_COMMENTS",
# "PigmentsFlag", "PIGMENTS_FLAG",
# "Pressure_dbar", "PRES_REL",
# "Pressure_flag", "PRES_REL_quality_control",
# # "Prochlorococcus_CellsmL", "Prochlorc_cellsmL",
# # "Prochlorococcus_flag", "Prochlorc_flag",
# "Region", "REGION",
# "SPCode", "SPCODE",
# "Salinity_Comments", "SALINITY_COMMENTS",
# "Salinity_flag", "SALINITY_FLAG",
# "Salinity", "SALINITY_PSU",
# "SampVol_L", "SAMPVOL_L",
# "SampVol_m3", "SAMPVOL_M3",
# "Sample", "SAMPLE",
# "SampleDate_UTC", "SAMPLEDATEUTC",
# "SampleDate_Local", "SAMPLEDATELOCAL",
# "SampleDepth_m", "SAMPLEDEPTH_M",
# "ScientificName", "SCIENTIFICNAME",
# "Silicate_flag", "SILICATE_FLAG",
# "Silicate_umolL", "SILICATE_UMOLL",
# "SizeRef", "SIZEREFERENCE",
# "Species", "SPECIES",
# "StartDate", "STARTDATE",
# "Synecochoccus_CellsmL", "Synechoc_cellsmL",
# "Synecochoccus_flag", "Synechoc_flag",
# "TAlkalinity_Comments", "TALKALINITY_COMMENTS",
# "TAlkalinity_flag", "ALKALINITY_FLAG",
# "TAlkalinity_umolkg", "TALKALINITY_UMOLKG",
# "TaxonCount", "CELL_COUNT",
# "TSS_Comments", "TSS_COMMENTS",
# "TSS_flag", "TSS_FLAG",
# "TSS_mgL", "TSS_MGL",
# "TaxonCount", "TAXON_COUNT",
# "TaxonGroup", "TAXON_GROUP",
# "TaxonName", "TAXON_NAME",
# "Temperature_degC", "TEMPERATURE_C",
# "Temperature_flag", "TEMP_quality_control",
# "TowType", "TOWTYPE",
# "Turbidity_NTU", "TURB",
# "Turbidity_flag", "TURB_quality_control",
# "Vessel", "VESSEL",
# "Volume_m3", "VOLUME_M3",
# "WaterDensity_flag", "DENS_quality_control",
# "WaterDensity_kgm3", "DENS",
# "WaterDepth_m", "DEPTH_M",
# "ZoopAbund_m3", "ZOOP_ABUNDANCE_M3",
# "i_Sample", "I_SAMPLE_ID"
